---
- hosts: webservers
  remote_user: root
  tasks:
  - name: allow ssh root access for team
    copy: src=files/.ssh dest=/root/ owner=root group=root mode=700

- hosts: supernodes
  vars_files:
    - vars/sites.yml
  tasks:
  - name: set site_selection (supernode)
    set_fact: site_selection=own
    when: is_supernode[ansible_hostname] is defined
    tags: [ fastd ]
  - name: set site_selection (no supernode)
    set_fact: site_selection=all
    when: is_supernode[ansible_hostname] is not defined
    tags: [ fastd ]

- hosts: supernodes
  sudo: True
  vars_files:
    - vars/greTunnels.yml
    - vars/fastd.yml
    - vars/sites.yml
  roles:
  - supernodes
  - slave-ns

- hosts: firmware-hosts
  remote_user: root
  tasks:
  - name: update apt cache
    apt: update_cache=yes cache_valid_time=3600
  - name: install packages to build gluon
    apt: name={{ item }} state=present
    with_items:
    - vim
    - tcpdump
    - less
    - screen
    - wget
    - sudo
    - coreutils
    - build-essential
    - subversion
    - git
    - libncurses5-dev
    - zlib1g-dev
    - unzip
    - gawk
    - libssl-dev # not mentioned in doc
  vars_files:
    - vars/fastd.yml
    - vars/sites.yml
  roles:
  - fastd

- hosts: webservers
  remote_user: root
  roles:
  - webservers
  - buildbot

- hosts: authorative-nameservers
  remote_user: root
  vars_files:
    - vars/sites.yml
  roles:
  - master-ns
