- name: install apt-transport-https
  sudo: True
  apt: name=apt-transport-https
- name: add fastd repo
  sudo: True
  apt_repository: repo="deb https://repo.universe-factory.net/debian/ sid main"
  # there are only packages in 'sid' there
  when: ansible_distribution == 'Debian'
- name: add fastd repo key
  apt_key: id=6664E7BDA6B669881EC52E7516EF3F64CB201D9C url=https://sks-keyservers.net/pks/lookup?op=get&search=0x16EF3F64CB201D9C state=present
- name: install fastd
  sudo: True
  apt: name=fastd update_cache=yes
- name: create fastd config dirs
  file: dest=/etc/fastd/{{ item.key }} state=directory
  tags: [ fastd ]
  with_dict: site_partitions[site_selection]
- name: write fastd keys # should not be logged
  lineinfile: dest=/etc/fastd/{{ item.key }}/secret.conf create=yes mode=0600 line='secret "{{ fastd_secret }}";'
  with_dict: site_partitions[site_selection]
  when: fastd_secret is defined
  tags: [ fastd ]
- name: write fastd configs
  template: src=fastd.conf.j2 dest=/etc/fastd/{{ item.key }}/fastd.conf
  with_dict: site_partitions[site_selection]
  tags: [ fastd ]
  notify: restart fastd
- name: write fastd blacklist.sh
  template: src=blacklist.sh.j2 dest=/etc/fastd/{{ item.key }}/blacklist.sh mode=750
  with_dict: site_partitions[site_selection]
  tags: [ fastd ]
