- name: add debian backports repo # letsencrypt
  apt_repository: repo="deb http://ftp.hosteurope.de/mirror/ftp.debian.org/debian/ jessie-backports main"
  when: ansible_distribution == 'Debian'
  notify:
    - update apt cache
- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
- name: install apache
  apt: name=apache2 state=installed
- name: enable mod_proxy_http
  apache2_module: state=present name=proxy_http
  notify:
  - reload apache
- name: configure apache virtual hosts
  template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ item.name }}.conf
  with_items: virtualHosts
  notify:
  - reload apache
- name: enable apache virtual hosts
  file: src='/etc/apache2/sites-available/{{ item.name }}.conf' \
    dest='/etc/apache2/sites-enabled/{{ '000-' if (item.default is defined and item.default) else '' }}{{ item.name }}.conf' \
    owner=root group=root state=link
  with_items: virtualHosts
  notify:
  - reload apache
  tags: [t2]
- name: create root directory for web content
  file: dest=/var/www/{{ item.name }} state=directory
  with_items: virtualHosts
- name: create directories for web content
  file: dest=/var/www/{{ item.0.name }}/{{ item.1.name }} mode={{ item.1.mode }} owner={{ item.1.owner }} state=directory
  with_subelements:
    - virtualHosts
    - directories
- name: copy web content
  synchronize: src=files/{{ item.1 }}/ dest=/var/www/{{ item.0.name }}/{{ item.1 }}
  with_subelements:
    - virtualHosts
    - files
- name: add thinserv2 repo
  apt_repository: repo="deb http://thinserv2.at-inet.de/~benedikt/deb/ jessie main"
  when: ansible_distribution == 'Debian'
- name: add thinserv2 repo key
  apt_key: id=38F77DA6226BC47BCE23B1EEAB020A3A42293620 url=https://sks-keyservers.net/pks/lookup?op=get&search=0xAB020A3A42293620 state=present
- name: install python-cryptography
  apt: update_cache=yes name=python-cryptography default_release=jessie-backports state=latest
  when: ansible_distribution == 'Debian'
- name: install letsencrypt
  apt: update_cache=yes name=python-letsencrypt-apache
  when: ansible_distribution == 'Debian'
- name: link for webserver to gluon beta
  file: src=/var/www/gluon/v2016.1.x/gluon/out/ dest=/var/www/download.ffnef.de/firmware/beta state=link
  tags: [ buildbot ]
- name: link for webserver to gluon experimental
  file: src=/var/www/gluon/master dest=/var/www/download.ffnef.de/firmware/broken state=link
  tags: [ buildbot ]
- name: place script to get gluon build
  template: src=get-build.j2 dest=/usr/local/sbin/get-build mode=0755
  tags: [ buildbot ]
