- name: generate /etc/network/interfaces.d/gre
  template: src=network-interfaces-d-gre.j2 dest=/etc/network/interfaces.d/gre
  tags: [ ffrlbb ]
- name: install bird
  apt: name=bird update_cache=yes cache_valid_time=3600
  tags: [ ffrlbb ]
- name: write bird ipv4 configuration
  template: src=bird.conf.j2 dest=/etc/bird/bird.conf
  notify: reload bird
  tags: [ ffrlbb ]
- name: write bird ipv6 configuration
  template: src=bird6.conf.j2 dest=/etc/bird/bird6.conf
  notify: reload bird6
  tags: [ ffrlbb ]
- name: activate ip forwarding via sysctl
  copy: src=90-forwarding.conf dest=/etc/sysctl.d/
  notify: restart procps
  tags: [ routing ]
- name: fix icmp forwarding via sysctl
  copy: src=90-icmp-replies.conf dest=/etc/sysctl.d/
  notify: restart procps
  tags: [ routing ]
- name: install bridge-utils (needed by ifup for bridges)
  apt: name=bridge-utils update_cache=yes cache_valid_time=3600
- name: configure bridge and dummy interfaces for freifunk
  template: src="network-interfaces-d-ff.j2" dest=/etc/network/interfaces.d/ff
  tags: [ bridges ]
- name: install ferm
  apt: name=ferm update_cache=yes cache_valid_time=3600
- name: configure ferm
  template: src="ferm.conf.j2" dest=/etc/ferm/ferm.conf
  notify: reload ferm
- name: install isc-dhcp-server
  apt: name=isc-dhcp-server update_cache=yes cache_valid_time=3600
  tags: [ dhcp ]
- name: configure dhcp-server
  template: src="dhcpd.conf.j2" dest=/etc/dhcp/dhcpd.conf
  notify: restart isc-dhcp-server
  tags: [ dhcp ]
- name: install bind9
  apt: name=bind9 update_cache=yes cache_valid_time=3600
- name: install radvd
  apt: name=radvd update_cache=yes cache_valid_time=3600
- name: configure radvd
  template: src="radvd.conf.j2" dest=/etc/radvd.conf
  notify: reload radvd
- name: name rt_tables
  copy: src=rt_tables dest=/etc/iproute2/rt_tables
- name: rc_local
  template: src=rc.local.j2 dest=/etc/rc.local
