- name: generate /etc/network/interfaces.d/gre
  template: src=network-interfaces-d-gre.j2 dest=/etc/network/interfaces.d/gre
- name: install bird
  apt: name=bird update_cache=yes cache_valid_time=3600
- name: write bird configuration
  template: src=bird.conf.j2 dest=/etc/bird/bird.conf
  notify: reload bird
- name: install bridge-utils (needed by ifup for bridges)
  apt: name=bridge-utils update_cache=yes cache_valid_time=3600
- name: configure bridge and dummy interfaces for freifunk
  template: src="network-interfaces-d-ff.j2" dest=/etc/network/interfaces.d/ff
- name: install ferm
  apt: name=ferm update_cache=yes cache_valid_time=3600
- name: configure ferm
  template: src="ferm.conf.j2" dest=/etc/ferm/ferm.conf
  notify: reload ferm
- name: install isc-dhcp-server
  apt: name=isc-dhcp-server update_cache=yes cache_valid_time=3600
- name: configure dhcp-server
  template: src="dhcpd.conf.j2" dest=/etc/dhcp/dhcpd.conf
  notify: restart isc-dhcp-server
