- name: restart buildmaster
  service: name=buildmaster state=restarted
- name: restart buildslave
  service: name=buildslave state=restarted
- name: add thinserv2 repo key
  apt_key: id=38F77DA6226BC47BCE23B1EEAB020A3A42293620 url=https://sks-keyservers.net/pks/lookup?op=get&search=0xAB020A3A42293620 state=present
