- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
- name: install buildbot
  apt: name=buildbot state=installed
- name: create master directory for gluon
  command: /bin/su -s /bin/sh buildbot -c 'cd;buildbot create-master masters/gluon'
- name: configure master directory for gluon
  template: src=master.cfg dest=/var/lib/buildbot/masters/gluon/master.cfg
  notify: restart buildmaster
- name: enable buildmaster
  copy: src=etc-default-buildmaster dest=/etc/default/buildmaster
  notify: restart buildmaster
- name: create user gluon-builder
  user: name=gluon-builder home=/var/lib/buildbot/slaves/gluon-builder
- name: create master directory for gluon
  command: /bin/su -s /bin/sh gluon-builder -c \
    'cd;buildslave create-slave . localhost:9989 localhost-slave "{{ buildbotSlavePassword }}"'
# consider putting builder into a container/chroot
- name: admin info
  copy: src=gluon-builder-info-admin dest=/var/lib/buildbot/slaves/gluon-builder/info/admin
  notify: restart buildslave
